### ISSUE TITLE
Lowercased urls

### ISSUE THREAD

**Issue by mruz** [terralist/terralist#191]
I have `CloudFront` module. Terralist generated https://localhost/#/modules/test/cloudfront/aws/1.0.0 url. When I click on it, I get the response:
> The resource you're looking for was not found on the server.

Loads if I type https://localhost/#/modules/test/CloudFront/aws/1.0.0 by hand.

**Comment by valentindeaconu** [comment]
This is an interesting issue because I implemented case insensitivity via the SQL queries as you can see below for almost all attributes (modules names, providers names, authorities names, modules' providers' names).

https://github.com/terralist/terralist/blob/672f799adc2bbf0be4871861fae116af7d402df8/internal/server/repositories/module.go#L52

My first bet is this is a UI issue, but unfortunately, I'm not able to test it for a couple of days. 
Can you try to see if the API is able to resolve the lowercase URL? The following `curl` command should return a status code of 200:
```bash
curl -s --dump-header - -o /dev/null http://localhost/v1/modules/test/cloudfront/aws/versions
```

**Comment by mruz** [comment]
For the lowercase URL API responds with:
> "errors":"no module found with given arguments

**Comment by mruz** [comment]
I noticed another UI issue with URLs and pagination. On the second page info boxes for the modules have URLs from the first page :confused:

**Comment by valentindeaconu** [comment]
Sorry for the late reply, I did not had access to my setup to test and reproduce this bug. Indeed, there's an issue as I only added case insensivity for authority names (sorry).

Now, this problem has two possible fixes:
1. Use case-insensivity for module and provider names. IMO this is the most natural approach, is not like there's an use-case where an user might want to push two different modules, one called `cloudfront` and one called `CloudFront`;
2. Fix the bug in the UI: if the module is called `CloudFront`, the page it should be linked should also contain `CloudFront` in the URL and not lowercase it. The only argument I have in favor of this approach is that URLs should be case-sensitive, according to [w3.org](https://www.w3.org/TR/WD-html40-970708/htmlweb.html):
> URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive.

I will let this issue stand for few days as a RFC. If there's no argument pro or against any of them, I will go with the first approach as it provides an extra layer of assurance that Terralist will not allow weird edge cases.
 
 > I noticed another UI issue with URLs and pagination. On the second page info boxes for the modules have URLs from the first page 😕

Please open a different issue and provide some more information so I can reproduce and debug it. Thank you!

**Comment by mruz** [comment]
I'm happy with the first proposal.
