### ISSUE TITLE
Pagination issues

### ISSUE THREAD

**Issue by mruz** [terralist/terralist#194]
On the second page info boxes for the modules have URLs from the first page and number of pages is wrongly calculated. I have 24 modules, 8 items per page and pagination shows only 2 pages. Ref: https://github.com/terralist/terralist/issues/191

**Comment by valentindeaconu** [comment]
I identified the problem. Fortunately, was a tiny mistake on my side (not setting the `key` property on items). The fix is submitted, I will merge it soon.

Thanks for submitting this issue.

**Comment by valentindeaconu** [comment]
> I just tried dev build and for 22 modules I only have one page with 8 boxes.

**Comment by valentindeaconu** [comment]
> I can see the buttons, but they only show one page and the next button is disabled.

Okay, interesting, I tested it with 11 modules and it worked fine. I'll push 22 so I have the same scenario and try to reproduce it. Thanks for reporting it quickly.

**Comment by valentindeaconu** [comment]
I merged the fix. Can you please give it another try and let me know if everything is fine now?

**Comment by mruz** [comment]
Everything works now. Thanks for fixing.
