### ISSUE TITLE
Purpose of Trust Signature?

### ISSUE THREAD

**Issue by danielarcari** [terralist/terralist#229]
When working with [public Terraform Registry](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-release-publish), only the public "armored" key is required when setting up a user. Terralist also prompts for a Trust Signature, why is this different from Hashicorp's setup, and more importantly, after generating a gpg key, what is the process to generate a signature in the format expected by terralist?

**Comment by valentindeaconu** [comment]
This is a field mentioned in the [sample request](https://developer.hashicorp.com/terraform/internals/provider-registry-protocol#sample-response-1) in the provider registry protocol. As you can see, even in the documentation it is not documented and neither HashiCorp is using it for their providers (latest aws provider [here](https://registry.terraform.io/v1/providers/hashicorp/aws/5.46.0/download/linux/amd64)). The field is not required in Terralist, so you can just leave it empty if you don't need it.

You can see [here](https://teknikaldomain.me/post/pgp-trust-levels-and-sig-types-explained/#trust-signature) what a trust signature is.
