### ISSUE TITLE
Can't download module in proxy mode

### ISSUE THREAD

**Issue by immogish** [terralist/terralist#290]
I'm trying to use proxy mode for modules.

I have uploaded tgz-archive with module to my artifact storage and did this request
```
curl -X POST https://terralist.mydomain/v1/api/modules/my-module/local/0.3.0/upload \
  -H "Authorization: Bearer x-api-key:token" \
  -d '{ "download_url": "https://storage.mydomain/terraform-modules/my-module/0.3.0/my-module-local-0.3.0.tgz" }'
```
, and all is ok(output is `{"errors":[]}`), i had a module in registry

But when i try to use module, i get this error:
```
│ Error: Error accessing remote module registry
│ 
│ Failed to retrieve a download URL for terralist.mydomain/test/my-module/local 0.3.0 from
│ terralist.mydomain: failed to get download URL for
│ "terralist.mydomain/test/my-module/local": 204 No Content resp:
```

I've maked request 
```
curl -i  https://terralist.mydomain/v1/modules/test/my-module/local/0.3.0/download -H "Authorization: Bearer x-api-key:token" 
```
 and discovered, that there was no needed header with url in response:
```
HTTP/2 204 
content-type: application/json; charset=utf-8
date: Sat, 29 Jun 2024 14:05:29 GMT
```

I've connected to the host and inspected the database:
```
sqlite> SELECT * from module_versions;
062b3e13-769f-4338-be95-d3048f33c20b|2024-06-28 14:39:56.111578362+00:00|2024-06-28 14:39:56.111578362+00:00|cc0ad2da-ce8b-4296-9447-0c671e261402|0.3.0|
```
and for some reason, there was an empty location. I've inserted location manually with update statement
```
UPDATE module_versions SET location = "https://storage.mydomain/terraform-modules/my-module/0.3.0/my-module-local-0.3.0.tgz" WHERE id = "062b3e13-769f-4338-be95-d3048f33c20b";
```
and now all works fine. Obviously, it's not correct behaviour, but i can't understand, is it any mistake in configuration, or something else?
i'm using 0.5.1 version

**Comment by immogish** [comment]
I think i have found cause of that: in proxy mode location isn't stored, because resolver in proxy mode is nil
https://github.com/terralist/terralist/blob/master/internal/server/services/module.go#L97-L122

i've fixed it in [my branch](https://github.com/immogish/terralist/commit/d986ae1a5cabaf8861a0d3322d3212293e915ff1), build it and all works as expected. Is it a valid fix?

**Comment by valentindeaconu** [comment]
Hello!
Yes, the fix in your branch seems legit to me. Can you open a PR with it?
Thanks for looking into it!
