### ISSUE TITLE
Add Metadata to the modules

### ISSUE THREAD

**Issue by vishnukv-facets** [terralist/terralist#344]
Hi, I have a use case where i upload a particular module and along with it some metadata.
Metadata being dependencies
for example:
the module the i upload A takes another module as input B,  so i want to add the metadata about B to module A like the supported versions etc..

is this currently possible?

**Comment by valentindeaconu** [comment]
Hello! This is not currently supported as of now, but I am planning to do this in the near future (when Terralist will have documentation generation).
As far as I know, this should not affect functionality, as Terraform/OpenTofu is able to automatically detect that your module is using a submodule and download that too. Although, I might be wrong, but I am pretty sure this works with git sources.

**Comment by vishnukv-facets** [comment]
Yes, thank you for the clarification
