### ISSUE TITLE
Current binary cannot be started

### ISSUE THREAD

**Issue by tszebeni** [terralist/terralist#357]
Hi dear terralist devs,
 I experience startup issue when I follow the official getting started guide for both linux and windows.
Please recommend or fix, Thanks

`
{"level":"error","time":"2024-11-23T10:49:53+01:00","message":"failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"}
{"level":"error","error":"Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub","time":"2024-11-23T10:49:53+01:00"}
`

`
terralist v0.5.2
Info:
 Commit Hash: b75a6ad
 Build Timestamp: 2024-09-16T12:34:18
`

**Comment by valentindeaconu** [comment]
Hello! Thank you for reporting this. The sqlite driver used by Terralist requires CGO to run. Some time ago I was using another driver who didn't. It looks when I upgraded to the new one, I forgot to remove the `CGO_ENABLE` variable from the goreleaser configuration. I created a PR to fix it, in the meanwhile, the container images should work fine. 
I will release a fix as soon as possible.

**Comment by tszebeni** [comment]
Hi @valentindeaconu , I can confirm it works.
Thanks
